### ISSUE TITLE
换小号测试一下

### ISSUE THREAD

**Issue by postint** [HugoPhi/HugoPhi#1]
### 🤝 Contact Details

hugonelson07@outlook.com

### 🤔 What happened?

nothing.
[release1-2.zip](https://github.com/user-attachments/files/18136875/release1-2.zip)
![2024-08-24_16-40](https://github.com/user-attachments/assets/9497f8dd-62df-4e89-b3f4-7ecda4af7ea1)

### 🔥 Question Type

Mathematic, Mathine Learning, About my project (no! \doge), Asking for recommends about software, Usage of ubuntu, A bug🐞 of a program, Some topic you want to discuss with me

### 🗃️ Expected answer.

A beautiful girlfriend😭 ... okey just for kidding😆.

### Are you in a hurry to solve this problem?

- [x] Yes

**Comment by HugoPhi** [comment]
good!
